version: "3"

services:
  app:
    container_name: devbox
    build:
      context: .
    command: sleep infinity
    volumes:
      - ".:/workspace:cached"
    networks:
      - dev

  db:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: jimlahey
      MONGO_INITDB_ROOT_PASSWORD: iamtheliquor
      MONGO_INITDB_DATABASE: eqscan
    volumes:
      - mongodb-data:/data/db
    networks:
      - dev

volumes:
  mongodb-data:

networks:
  dev:
