// <auto-generated />
using EqScan.Api.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace EqScan.Api.Migrations
{
    [DbContext(typeof(EqScanDbContext))]
    partial class EqScanDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.11")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("EqScan.Common.Contact", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Contacts");

                    b.HasData(
                        new
                        {
                            Id = "1",
                            Email = "jlahey@sunnyvale.com",
                            Name = "Jim Lahey",
                            Phone = "(843)230-5555"
                        },
                        new
                        {
                            Id = "2",
                            Email = "randy@sunnyvale.com",
                            Name = "Randy",
                            Phone = "(843)230-5556"
                        });
                });

            modelBuilder.Entity("EqScan.Common.Unit", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ContactId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("UnitType")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ContactId");

                    b.ToTable("Units");

                    b.HasData(
                        new
                        {
                            Id = "1",
                            ContactId = "1",
                            UnitType = "Radio"
                        },
                        new
                        {
                            Id = "2",
                            ContactId = "2",
                            UnitType = "Radio"
                        });
                });

            modelBuilder.Entity("EqScan.Common.Unit", b =>
                {
                    b.HasOne("EqScan.Common.Contact", "Contact")
                        .WithMany("Units")
                        .HasForeignKey("ContactId");

                    b.Navigation("Contact");
                });

            modelBuilder.Entity("EqScan.Common.Contact", b =>
                {
                    b.Navigation("Units");
                });
#pragma warning restore 612, 618
        }
    }
}
